on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd)
      - name: Display Coding Style Errors
        if: ${{ steps.check_coding_style.outcome == 'failure' }}
        run: echo ::error ::$(cat coding-style-reports.log)
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - run: make
        timeout-minutes: 2
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - run: make tests_run
        timeout-minutes: 2
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [check_coding_style, run_tests]
    steps:
      - uses: actions/checkout@v2
      - name: Mirror Repository
        env:
          MIRROR_URL: ${{ secrets.MIRROR_URL }}
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        run: |
          git clone --mirror "$MIRROR_URL"
          cd "$(basename "$MIRROR_URL")"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin "$MIRROR_URL"
          git checkout -b "${GITHUB_REF#refs/heads/}"
          git reset --hard "${GITHUB_SHA}"
          git push --mirror