on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-1-chocolatine-raoufi.kora.git"
  EXECUTABLE: "mysh"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd)
      - name: Display Coding Style Errors
        run: |
          while IFS= read -r line; do
            fields=($(echo "$line" | cut -d':' -f1-));
            echo "::error title=Coding Style Error file=${fields[0]} line=${fields[1]}::${fields[2]}"
          done < /coding-style-reports.log
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
      - run: make
        timeout-minutes: 2
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
      - run: make tests_run
        timeout-minutes: 2
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [check_coding_style, run_tests]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}