name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:                  
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@github.com:<Salem20050>/<Bootstrap_chocolatine>.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}